### ISSUE TITLE
Remember accepted profile warnings

### ISSUE THREAD

**Issue by pixeldesu** [swmff/sparkler#11]
Currently, when visiting a profile with a profile warning, you have to accept the warning on every visit. For improved usability it'd be cool if the site remembered if we accepted the warning before.

**Note:** This should take into account that people might change their profile warning (for whatever reason), so maybe a hash of the content should be stored as state when a warning has been accepted, so in case the warning changed, it can be shown again even when previously accepted.

**Comment by trisuaso** [comment]
Fixed, thank you!

This is done fully on client (stored in `localStorage.accepted_warnings`) because there's no need to store extra stuff like this on the server.

The hash is checked by client JS against the stored hash that we previously accepted. The warning will be shown again if the hash is different.
